### ISSUE TITLE
HistogramLogWriter not supporting  'outputValueUnitScalingRatio' ?

### ISSUE THREAD

**Issue by clifford** [HdrHistogram/HdrHistogram#112]
Hi 

I am using HdrHistogram to record the rate of messages/second, using a combination of, SingleWriterDoubleRecorder (to record double values) and HistogramLogWriter for outputting the encoded histogram (as is done in jhiccup).
What I've observed, is that I get different results from using the above combination, as opposed to using the DoubleHistogram directly. The encoded version, does not seem to honour the, 'outputValueUnitScalingRatio'.

Histogram scales the values before being output by the 'outputValueUnitScalingRatio'. Is there a way to make the HistogramLogWriter do the same?

Am I missing something? should I be using something other than HistogramLogWriter to output the encoded double histogram?

Any help would be greatly appreciated.

Clifford

**Comment by giltene** [comment]
Hopefully I'm clear on the question: you are looking to report on values in a log with a similar unit scaling option to the one you have with Histogram.outputPercentileDistribution() , where you can provide a outputValueUnitScalingRatio parameter. Is that correct?

If that's so, the place to do that is [probably] not in the log writing itself, as the log writer maintains the logged histograms in their natural internal units. Instead, the unit transformation is probably best done while in processing the log. For example, the HistogramLogProcessor utility already supports a -outputValueUnitRatio that would perform the bit scaling on the report you generate from a histogram log. You can mimic that behavior in your own log readers if you wish (which would likely use HistogramLogReader to invest histograms from a log.

Separately, capturing the units used for logged histograms so that they can be normalized to by log readers is an issue that is separately tracked in https://github.com/HdrHistogram/HdrHistogram/issues/109
