### ISSUE TITLE
add method double getMeanBelowPercentile(final double percentile)

### ISSUE THREAD

**Issue by jiming** [HdrHistogram/HdrHistogram#116]
Hi guys,

Most time I do not like the whole mean time, I just wanted the mean time below 99.9%. Could you please consider add a method to get the mean time by percentile.

Thanks a lot!
Jiming

**Comment by nitsanw** [comment]
@jiming what does that number represent? how is it generally useful?

**Comment by jiming** [comment]
@nitsanw 
Usually,  when some exception happened, getValueAtPercentile(0.999) can be very high than other value. And which will pull up the mean value as well, I wanted the mean value exclude the exception high value.
For example, I have value [1,2,1,2,1,2,99], I wanted get the mean value without 99.

Thanks!
Jiming

**Comment by mikeb01** [comment]
If you are look for an "average" that is less affected by the outliers, then the median (i.e. 50%'ile) would be a better option.

**Comment by nitsanw** [comment]
@jiming I'm not sure I see this as generally useful... and you can already achieve this via the iterators. It seems like you want to call something "99%ile" but without the unpleasant side effect of including outliers that are in the 99%ile. This is not something I think is advisable, and I hope it is not general practice. As @mikeb01 suggests, a 50%'ile is a better choice.

**Comment by jiming** [comment]
Dear @mikeb01  @nitsanw 

Is there any theory ,article or wiki says that 50% is better thant average of 0%-99% please? 

Thanks!
Jiming

**Comment by nitsanw** [comment]
@jiming AFAIK "average of 0%-99%" is not a thing. Perhaps I've missed something. I would personally advise against this this metric which is non-standard and potentially misleading (as someone might think it's indicative of the 99%ile, which it probably isn't see some of @giltene articles/talks on averages, and averages of percentiles). Regardless, if it is not standard I don't think it warrants an expansion of the API.
Do you have any sources supporting the use of this metric, in particular for latency data?

**Comment by jiming** [comment]
@nitsanw 

I do not have a theory about it. I think it is useful because some competition TV show, there have dozens of judges score for actors. When every judges give the score, to calculate the last score, they will exclude the two highest score and two lowest score, and average the rest score. So they could exclude some noise of the data.

And I think since you supplied getMean(), why not supply getMeanBelowPercentile(final double percentile) ? Which make much more sense than getMean().

I just want to get a manner to exclude the noise data.

Thanks!

**Comment by giltene** [comment]
@jiming 

As others noted, you can already use iterators to perform pretty much any mathematical computation on the histogram data, and you can extend histograms to do that in a custom way by adding your own methods. This applies as much to a new getMeanBelowPercentile() method as it would to getFifthHighestEvenNumberBelowPercentile().

In the base implementation, we try to stick to commonly used capabilities, leaving more exotic and custom treatments of the data sets for downstream users to implement by themselves. I say this without judging the advisability of using a specific calculation. If your use for HdrHistogram is the studying of the distribution of pitch in baboon cries in Chacma baboon populations, your calculation may well be useful [I really don't know]. If what you are studying is response time or latency, it is decidedly not useful. The choice of including it as a method in the HdrHistogram base classes is driven by whether or not it is commonly used.

For example, we've included mean and standard deviation calculations NOT because they are meaningful in all cases (e.g. both produce meaningless values when when studying response time and latency data, and using them is a bad practice and anti pattern in that space) but because they are commonly used computations on histogram'ed data (e.g. when histogram'ing colors, average and std deviation may be useful). In doing that, we have not gone into exhaustively adding computations. I would probably add methods for common statistical characterization of semi-normal distributions, like getKurtsis(), getSkewness(), getLmoment(), well before adding some of the more custom things like discussed here...

**Comment by jiming** [comment]
@giltene 

Please take a look at the timer metric of my system

https://github.com/jiming/versions/blob/master/resources/sla.jpg

From time to time, there have 99.9 timer is very high than others, which would cause the MEAN error. That's the reason I wanted to exclude 99.9 when calculating the mean.

I can understand that add an API should be very careful. So is it possible to add a HistogramHelper class and add the method in that class. And which will not pollute the Histogram API.

It is kind of difficult for me to understand the algorithm of HdrHistogram, so I am not able to implement it by myself. If you do not plan to add the API, could you guys please kindly write the code, so that I can just copy the source code in my code? If it is not easy , just ignore it, I already appreciate your time very much.

Thanks a lot for you patience and great answer!

Jiming

**Comment by ennerf** [comment]
@jiming 

I'm assuming that the game shows you mentioned do this because people are not very accurate at objectively judging other people, which results in outliers, and because they can usually only choose discrete values, e.g., 1-5. Thus, the median would only ever return one of 5 values, which is insufficient for ranking lots of people.

Your graph looks like you are measuring some sort of latency in milliseconds. Assuming that your timer is working properly (if not, I'd recommend writing an algorithm that detects outliers rather than throwing away the worst X), it would indicate a problem in your system. Let's say you have 1000 measurements. 99.9% are exactly at 220ms, but the mean shows up as 1.220ms. This would require the worst 0.01% to be ~1E6 seconds, which is about 16.6 minutes. Since the bars in your graph look like they are about 1 minute apart, you probably have less than 1000 measurements and calculating the mean of the best 99.9% would result in the same value.

I'd recommend you to look at some of the talks and posts on how to measure latency with HdrHistogram to better figure out what's going on in your system. Hint: If you are using Java, it's probably GC.

**Comment by giltene** [comment]
@jiming 

It's not clear what "SLA API" means in the chart you link to above, or what is being plotted...

However, if this is an attempt to describe the behavior of response time or latency, then using the mean as a way to describe what is going on is already wrong. And "cleaning up the mean" by ignoring values above a certain percentile will only make it more wrong.

When it comes to describing latency, here is a simple slogan: "The mean is meaningless."

See http://latencytipoftheday.blogspot.com/2014/06/latencytipoftheday-average-random.html for some discussion of this.

If you are looking for something that describes "the common case" or "where most latencies lie", use a simple percentile (like the median). It will provide you with a number than actually happened, and probably with a better feel for "the neighborhood where most of the values are".

**Comment by giltene** [comment]
@jiming 

Separately from whether or not performing some mathematical transformation on the data set makes sense or not, you can do any such transformation by simply iterating over the values in the histogram. Subclass Histogram and add you own method to do that if you wish. You can look at how getMean() does it's job (e.g. https://github.com/HdrHistogram/HdrHistogram/blob/master/src/main/java/org/HdrHistogram/AbstractHistogram.java#L1242) for a simple example of iteration. And you can/should make your own RecordedValuesIterator...

**Comment by jiming** [comment]
@giltene @ennerf 

Thank you for your great reply!

I will see getMean as @giltene suggested.

@ennerf The case is just as you described. The 1.2s record is because one client use HTTP 100-continue header. And since the sever do not handle it, the client will wait 1s and then sending its request. This is not latency of server. So I wanted to exclude this kind of data from analysis to get a more accurate response time of server. Simply exlude certain percentage of data does not make sense and even draw wrong conclusion. But combime with other metrics, it would be helpful to drill down and troubleshooting. I would like to record **min, 50%, 80%, 95%, 99%, 99.9%,max, mean, meanBetween(0.1%,99.9%)**, and with all these data, it could be enough for me to troubleshooting and evaluating server performance.
