### ISSUE TITLE
support leap second

### ISSUE THREAD

**Issue by xuwei-k** [HdrHistogram/HdrHistogram#121]

**Comment by giltene** [comment]
Im not sure what this would entail. Histogram values are not assumed to have any units (could be nanoseconds, seconds, brightness, kilograms, bug numbers,  whatever), so leap second would not apply to that. And time stamps used (e.g. for travking start/end of reporting periods for logging purposes) use the common milliseconds-since-epoch unit, and leap-second issues would presumably be subdued by anything that consumes that.

I plan to close this s in the next couple of days if no further comments are added,
