### ISSUE TITLE
precision of the histogram

### ISSUE THREAD

**Issue by ArvinDevel** [HdrHistogram/HdrHistogram#128]
If I use a 90 days long histogram recorder, whether that might impact the precision of the histogram itself, is there a recorder duration upper limit

**Comment by giltene** [comment]
The HdrHistograms data structure, by design, is not sensitive to number of values recorded in it. Storage size is determined purely by the range and precision, and NOT by the count of recorded values. The only limit on the amount of information recorded in a histogram Recorder is that the total count cannot exceed Long.MAX_VALUE (which is 2^63 - 1). So e.g. at 1 billion recorded values per second, it would take an HdrHistogram Recorder ~272 years to overflow...
