### ISSUE TITLE
Make histogram classes extensible

### ISSUE THREAD

**Issue by gortiz** [HdrHistogram/HdrHistogram#130]
Hi there,
I'm trying to use HdrHistogram to improve the efficiency of binary search on a quite large array. The idea is to use HdrHistogram to register the distribution of the data on the array, so the first attempt to _binary_ search doesn't search from first to the last position, but on a subset calculated by using something like:

```
      long value
      ...
      long prev = histogram.lowestEquivalentValue(value) - 1;
      int offset = (int) histogram.getCountBetweenValues(0, value);
      limit = (int) histogram.getCountAtValue(value);
    
      Arrays.binarySearch(arr, offset, limit, value)
```

The performance of that implementation is horrible because getCountBetweenValues cost is O(n) on the buckets (I think). My next idea was to extend Histogram class so I can maintain an array like Histogram.counts but with the accumulated count, so histogram.getCountBetweenValues(0, value) can be calculated at constant time.

Bad news here, Histogram can be extended, but it is not very useful because abstract methods on AbstractHistogram are _package protected_ instead of _protected_, so only classes whose package is org.HdrHistogram can override them.

I cloned this repo and manually modified Histogram so:
- attribute counts is maked protected
- methods normalizedIndex(int) and getIndex(long) are protected

By doing that, I could create my own subclass that calculates the accumulative count and, by doing that, improved the performance of my search algorithm by 15%.

Could be possible to modify Histogram classes so their package protected methods are protected?

**Comment by giltene** [comment]
Hmm.. You present an interesting use case, and a cool example of extending the base HdrHistogram. The downside to [in general] exposing package-local methods as protected is that they then become part of the externally expected API and contract. This makes package-internal implementation details exposed, and limits future changes to that implementation. Not a good long-term architectural choice. As a specific example, very early versions of HdrHistogram did not use a flat counts array, and shifting and auto-sizing functionality was added over time. If we had exposed the internal array representation and semantics (e.g. with a protected getIndex()) earlier, we would not have been able to add some of the later functionality (e.g. the internal notion of normalizedIndex() used for shifting or auto-sizing).

Instead of exposing all package-local methods as protected, we could discuss the specific things you found a need to expose, examine alternatives, and see if exposing some specific methods in a way that does not expose internal implementation can be worked out.

E.g. you could achieve your extension by having your sub-class maintain it's own accumulatedCounts array (which I assume is what you did). You could then override the various data entry public methods (such as recordValue, etc.) and maintain your accumulatedCounts data, calling the base implementation public methods as needed to manage the package-internal semantics.  And you could override the public getCountBetweenValues() with your more efficient O(1) implementation that leverages the accumulatedCounts data.

In managing your own accumulatedCounts array, you would likely end up needing various support methods (such as getIndex(), normalizedIndex(), etc.). You could obviously replicate all those by copying the logic from the internal implementations (and apply it purely for managing your accumulatedCounts array). This would have the upside of remaining agnostic to future changes in HdrHistogram, but it would certainly be cumbersome, I can see how this would not be an attractive option... So lets try to think up some middle ground possibilities...

BTW, I would separately worry about how well you can keep your internal accumulatedCounts array managed and in-sync with the histogram's internal notions. E.g. the plain HdrHistogram may be easy to follow (you still need to properly cover resizing, copying, add/subtract, serialization and deserialization, encoding and decoding, but at least you have a simple, non-concurrent scenario to work with). Things get more complicated when you look at variants like ConcurrentHistogram, AtomicHistogram, etc. Now you may look at this from your point of view and say that you only see a need to extend the more basic HdrHistogram variant, but if/once we expose methods to subclasses, we'd need those methods to make sense to e.g. subclasses of ConcurrentHistogram as well, so we need them to be well thought out (something the current package-internal implementation didn't have to go through because we could always improve on it later).

**Comment by gortiz** [comment]
I understand your concerns related to make methods protected.

In my case, modifications are not a problem because the structure I am _indexing_ is immutable, so I only need to calculate the accumulatedCounts once. In fact, the method I have added creates a new accumulatedCounts array each time. I guess I can create that array by using one of the iterators, but I don't really know which one should I use and then I would need to replicate the index logic so I can transform a long into it's position on accumulatedCounts in constant time.

**Comment by giltene** [comment]
The AllValuesIterator is used to iterate over every distinguishable value in the histogram. The RecordedValuesIterator can be used to only visit the ones with non-zero counts.

**Comment by giltene** [comment]
Hmm... I reviewing this, I think there is a much cleaner way for you to implement what you want, which is a fast/hot implementation of getCountBetweenValues on a histogram that represents a fairly static value distribution in e.g. a large immutable structure. 

Don’t use an array to track the sum of the counts. Instead, use a histogram, one that is the “integral” of the values distribution histogram. I.e. to create it ( once the values distribution histogram is populated) iterate on the valuesDistributionHistogram, and record the total-counts-to-this-value in a countsToThisValueHistogram that has the same dimensional parameters (precision, rage). You can then look up the total counts up-to-and-including-any value in your valuesDistributionHistogram with countsToThisValueHistogram.getCountAtValue(), which is O(1), and getCountBetweenValues() is simply the difference between two calls to that.

You can even hide this in a histogram subclass that would hide this integral histogram inside, and populate it on the first getCountBetweenValues() call that occurs after any recording happens (override the recording methods to set a dirty flag, and override getCountBetweenValues to check it and rebuild if needed). Would be very slow first call after each mutation, but very fast once a stable set is loaded.

I’m going to close the issue at this point, as for the original subject (expose package private methods as protected) we have not identified any candidates with a strong (enough) argument for exposure that would outweigh the downsides.
