### ISSUE TITLE
RecordValueWithExpectedInterval compensation accounting for CO 

### ISSUE THREAD

**Issue by franz1981** [HdrHistogram/HdrHistogram#134]
Hi!

I wasn't sure to create this issue mainly due because it looks more like a question.

For what I'm seeing by looking at the `Histogram::recordValueWithExpectedInterval` code, it is an effective way to rebalance the weights of the samples accounting for the hidden discount that a coordinated omission would do.

Hence my expectation on this method is that given a load generator and a service to be measured that shows very early a big outlier (compared to the expected interval), the resulting histogram of the sampled service time will be "patched" somehow, resulting in higher values for lower percentiles:

![service_time](https://user-images.githubusercontent.com/13125299/33474482-168ed982-d67b-11e7-86bf-6f056c44f16b.png)

`CO_service_time` is measured by a load generator vs a service with a single initial big outlier and without accounting for CO omission on the samples, while `CO_patched_service_time` is the same but using `Histogram::recordValueWithExpectedInterval` with the expected rate of the load generator.

The result is fully matching my expectations, but what if the load generator and sampler already account for CO by recording the response time instead of service time?

![response_time_vs_service_time](https://user-images.githubusercontent.com/13125299/33474658-df0b332e-d67b-11e7-83d4-a9ebf667dc3a.png)

The graph is pretty explicative: the single point upper left is showing a far worst "latency" distribution but it fully matches what could be the UX by stressing that service.
The code [here](https://github.com/franz1981/HdrHistogram/blob/89ad66c1f39883d869b95a185a4e00a33a7c0406/src/test/java/org/HdrHistogram/HistogramTest.java#L374) is the source of these graphs.

That's my concern: `Histogram::recordValueWithExpectedInterval` is accounting for CO omission providing a "different view" of the service time or it is actually trying to mimic the response time?

I hope to not have messed up too much with terminology/concepts belonging to parallel worlds: the more I see this issue the more I'm thinking is a real (maybe naive) question.

**Comment by giltene** [comment]
The simple answer to the question is: You obviously shouldn't correct twice. The normal Histogram::recordValue method does no correction or compensation, and should be used whenever no correction or compensation is needed. Histogram::recordValueWithExpectedInterval is *a* means of compensating for missed measurements that may occur due to coordinated omission.

E.g. jHiccup (see https://github.com/giltene/jHiccup/blob/master/src/main/java/org/jhiccup/HiccupMeter.java#L479) is a classic example of a (IMO very common) situation where we know that our intentionally synchronous measurement will result in an unavoidable coordinated omission of some measurements, and where we also know exactly how to compensate for the missed measurements. It is a prototypical case where time interval measurement is expected to occur at a given rate, with a fixed intended interval between measurements, and that when a measurement that is larger than the intended inter-measurement interval is observed, we deterministically know that some required measurements were missed. We also deterministically know when those missed measurements *should* have occurred, and what their minimum possible values are.

The above is appropriate in cases where "if we didn't measure it at the right time, it is too late to do anything about it, and we have to compensate". However, when building load generators, one can do much better (wrk2, the latest YCSB on GitHub, and Cassandra Stress in C* 3.1 and above are all examples of this). Basically, if the generator has some scenario to follow, it should actually execute every operation in that scenario (and never ever give up on any), and take note of its completion time. The key to correct response time measurement in a load generator is to establish and keep track of the *expected* start time of each operation (per the scenario the generator is expected to follow), and to measure and record response time as the time between that expected start time and the eventual response. The actual start time at which the load generator got around to initiating the operation is immaterial to response time and is only useful for measuring service time. Confusing the actual start time with the expected start time (and using the wrong one) is the cardinal mistake many load generators make, which leads to coordinated omission in their reported response times. If that mistake is corrected (or never existed), Histogram::recordValueWithExpectedInterval is not needed, and using it will mess up the data...

**Comment by franz1981** [comment]
@giltene 
> The simple answer to the question is: You obviously shouldn't correct twice.

And it makes sense to me.
While reading my first "question" I've noticed wasn't clear enough, sorry for that...
![image](https://user-images.githubusercontent.com/13125299/38247820-d13baf22-3746-11e8-9671-8dabb998585d.png)

The red point on the (high) left is the response time distribution produced by a load generator that actually accounts for CO by:
- using the correct expected start time to measure it
- never give up on any sample

While the blue line is the service time patched by `HdrHistogram`: they are quite different...
My question is: how much are supposed to be different the latency distribution of the samples patched by `HdrHistogram` vs the real one using a CO aware load generator?
Maybe I'm missing something that doesn't allow to compare apples to apples.
