### ISSUE TITLE
ConcurrentModificationException in ConcurrentHistogram

### ISSUE THREAD

**Issue by Susi1** [HdrHistogram/HdrHistogram#155]
Caused by: java.util.ConcurrentModificationException
    at org.HdrHistogram.AbstractHistogramIterator.next(AbstractHistogramIterator.java:96)
    at org.HdrHistogram.PercentileIterator.next(PercentileIterator.java:18)
    at 

Getting ConcurrentModificationException while trying to iterate ConcurrentHistogram. I am using ConcurrentHistogram to record values(multi threaded environment).

**Comment by giltene** [comment]
Per the documentation (in e.g. 
http://static.javadoc.io/org.hdrhistogram/HdrHistogram/2.1.11/org/HdrHistogram/ConcurrentHistogram.html ) "...It is important to note that concurrent recording, auto-sizing, and value shifting are the only thread-safe behaviors provided by ConcurrentHistogram, and that it is not otherwise synchronized. Specifically, ConcurrentHistogram provides no implicit synchronization that would prevent the contents of the histogram from changing during queries, iterations, copies, or addition operations on the histogram. Callers wishing to make potentially concurrent, multi-threaded updates that would safely work in the presence of queries, copies, or additions of histogram objects should either take care to externally synchronize and/or order their access, use the SynchronizedHistogram variant, or (recommended) use Recorder or SingleWriterRecorder which are intended for this purpose."

For your use case (e.g. reporting on percentiles in a moving histogram) I would suggest a Recorder (http://www.javadoc.io/doc/org.hdrhistogram/HdrHistogram/2.1.11), it was designed for that exact purpose.
