### ISSUE TITLE
DoubleHistogram.getMaxValue() may return a value less than the recorded value

### ISSUE THREAD

**Issue by oertl** [HdrHistogram/HdrHistogram#178]
When doing some tests comparing the recording speed of various histogram data structures (see https://github.com/dynatrace-oss/dynahist/blob/1845e08428159fb7e7fc73e2f27d336462e4cc38/src/jmh/java/com/dynatrace/dynahist/RecordingSpeedBenchmark.java), I realized that the returned maximum value of `DoubleHistogram.getMaxValue()` may be less than the recorded value. The following code allows to reproduce my observation
```
DoubleHistogram histogram = new DoubleHistogram(1_000_000_000, 2);
histogram.recordValue(2.5362386543);
System.out.println(histogram.getMaxValue());
```
It gives `2.53125` as output which is clearly less than the recorded value.

Since [`DoubleHistogram.getMaxValue`](
https://github.com/HdrHistogram/HdrHistogram/blob/377de7da9b08c4f6cf159b3157f4a0e0492b9c39/src/main/java/org/HdrHistogram/DoubleHistogram.java#L1052) is based on [`AbstractHistogram.highestEquivalentValue`](https://github.com/HdrHistogram/HdrHistogram/blob/377de7da9b08c4f6cf159b3157f4a0e0492b9c39/src/main/java/org/HdrHistogram/AbstractHistogram.java#L1203) I would expect to get the upper bound of the histogram bucket, to which the recorded value was mapped to. The second paragraph of [this comment in issue 105](https://github.com/HdrHistogram/HdrHistogram/issues/105#issuecomment-227757910) also suggests to get an upper bound.

**Comment by giltene** [comment]
Thanks for flagging this. It occurred in situations where the max value fell in a range where the underlying integer sub-buckets were of 1 unit wide, such that the maximum equivalent value of an integer was the same as the integer value (the next highest value minus 1), but the maximum equivalent value of the equivalent double would be different ("1 ulp below the next highest value"). Fixed by applying the highestEquivalentValue conversion on the double value as well (highestEquivalentValue already deals with the "within 1 ulp of the next highest value" math).
