### ISSUE TITLE
Base64Helper.java using javax.*

### ISSUE THREAD

**Issue by ghost** [HdrHistogram/HdrHistogram#202]
Hi!

The class still uses javax.* references instead of jakarta.*; can you guys update it?

Thanks!

**Comment by jerrinot** [comment]
@ghost: This looks very much intentional to me. 
It's meant to be used on Java SE 7 - `javax.xml.bind.DatatypeConverter` is included in this platform. If you are on Java SE 8+ then it's used `java.util.Base64`.

**Comment by giltene** [comment]
Right. HdrHistogram carefully avoids external dependencies so far, and is also actively used across a wide range of Java SE versions. As such the “dance” used to only leverage built-into-the-JavaSE-JDK Base64 encode/decode capabilities is intentional, and was brought on by the (breaking) shifts in Base64 API support in Java SE over time. The reasons for this  helper’s existence are detailed in its javadoc comments. When support for Java SE 7 is eventually dropped at some future date, the helper will no longer be needed and the code will likely be refactored to directly use java.util.Base64.
