### ISSUE TITLE
getTotalValueToThisValue() gone from HistogramIterationValue

### ISSUE THREAD

**Issue by lenborje** [HdrHistogram/HdrHistogram#57]
The method ``HistogramInterationValue.getTotalValueToThisValue()`` seems to be gone. (Parts of my code made good use of it.)

Is this deliberate or a bug? The JavaDoc for ``HistogramInterationValue`` still mentions the corresponding property.

If it is deliberate, is there a recommended suggestion for refactoring its use?

I've used this method to produce "moving mean" graphs, plotting ``totalValueAtThisValue/totalCountAtThisValue`` over ``valueIteratedTo``. This gives a rather informative graph showing how the mean is influenced by outliers in the data.

**Comment by giltene** [comment]
This is fixed with https://github.com/HdrHistogram/HdrHistogram/commit/9ff34a11d1c30b7d133a86a34397baadf28310bf

Dropping it in 2.1.0 was a result of a couple of issues, including rationalizing the behavior for DoubleHistograms and questions about what the proper value to sum up would be (it used to sum up the median equivalent values, which caused some inconsistencies).

In the re-introduced version, getTotalValueToThisValue() sums up consistently with valueIteratedTo() : both use highestEquivalentValue as their choice for representing values iterated to or over.

**Comment by lenborje** [comment]
Thank you; works as a charm!
