### ISSUE TITLE
Compilation error 

### ISSUE THREAD

**Issue by ettoremaiorana** [HdrHistogram/HdrHistogram#62]
Hello and thanks for this tool.

I'm trying to build from source, but I get the following error.

[ERROR] ./git/HdrHistogram/src/main/java/org/HdrHistogram/AbstractHistogram.java:[1799,36] error: getEncodingCookie() has private access in AbstractHistogram
[ERROR] ./git/HdrHistogram/src/main/java/org/HdrHistogram/AbstractHistogram.java:[1800,40] error: getV0EncodingCookie() has private access in AbstractHistogram
[ERROR] ./git/HdrHistogram/src/main/java/org/HdrHistogram/AbstractHistogram.java:[1850,17] error: fillCountsArrayFromSourceBuffer(ByteBuffer,int,int) has private access in AbstractHistogram

And this is the environment:
-Xmx4g -XX:MaxPermSize=256m
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.04.2)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

I can fix it locally extending the visibility of those methods, but I thought it was worth making you aware of this.

Thanks,
Ivan Valeriani

**Comment by giltene** [comment]
Fixed with https://github.com/HdrHistogram/HdrHistogram/commit/72b16d8cb01c9238ccf35e105d4e564a1c1588b9

Interestingly, this is NOT a compilation error on Java 6, but is on Java 7 and Java 8. I've been building with Java 6 to make sure it works across versions, but it looks like javac in later Java versions has decided to be more picky about private access to a base class fields/methods of a generic type (T extends AbstractHistogram) from within that base class's own methods.
