### ISSUE TITLE
AbstractHistogram overrides equals without overriding hashcode

### ISSUE THREAD

**Issue by slandelle** [HdrHistogram/HdrHistogram#81]
As expected when failing to properly override both hashcode and equals, one would get crazy random bugs when storing histograms in hash based structures.

I see 2 solutions:
* either implement hashcode
* or rename `equals` override into something like `isEquivalentTo`

**Comment by giltene** [comment]
Good point. Added hashCode() to both AbstractHistogram and DoubleHistogram, and modified equals to allow histograms with identical value contents but different configured ranges to be equal (much more relevant since auto-sizing was introduced). Addressed with https://github.com/HdrHistogram/HdrHistogram/commit/a55c40ffb4c8df4c21d9cd4db34855da1b30e1d4

Note that this only partly addresses the issue of using histograms in hash based data structures. Since histograms are mutable, and their equals() (and therefore hashCode()) behaviors depend on their mutable state, it would be a bad idea to use a mutating histogram's hashCode in hash based data structures (e.g. as the key in a hashmap)...
 
Out of curiosity, where did you run into a need for using a histogram as a key in a hash-based structure?

**Comment by slandelle** [comment]
> Out of curiosity, where did you run into a need for using a histogram as a key in a hash-based structure?

It was actually my being lazy and both using an inappropriate structure and not checking the code. I used Scala `MultiMap` (which is basically a `HashMap[K, HashSet[V]]`) to perform some grouping, where V is some case class hierarchy that contains some histograms.

I never intended to deal with histogram "duplicates" but it didn't occur to me that you could have actually overridden equals, so I thought I was using the default Object impl and I never try to add the same instance. Then, my unit tests failed randomly because of the missing hashcode override, which gave me some headaches :)
