### ISSUE TITLE
ArrayIndexOutOfBoundsException when copying a resizable ConcurrentHistogram

### ISSUE THREAD

**Issue by slandelle** [HdrHistogram/HdrHistogram#87]
Hi Gil,

I sometimes have an `ArrayIndexOutOfBoundsException` when copying a resizable ConcurrentHistogram.

It looks to me there's a race condition in `AbstractHistogram#add`: even if the [target is resized before copying](https://github.com/HdrHistogram/HdrHistogram/blob/master/src/main/java/org/HdrHistogram/AbstractHistogram.java#L586), it's perfectly possible that the original `countsArrayLength` is expended during the copy, causing an `ArrayIndexOutOfBoundsException`.

**Comment by giltene** [comment]
I think that this is now addressed with https://github.com/HdrHistogram/HdrHistogram/commit/c2f33887b56530fd4cfa10a541697288bb1af794 , which should prevent the issue when adding into a resizable histogram. Presumably, this race could only have happened if the source histogram for the add was being recorded to concurrently with the add call.

Since I don't have a test that shows the race-condition-triggered OOB to demonstrate that it goes away. Can you test to verify?

Separately, there is an obvious raciness to adding data from a concurrent histogram that is being actively recorded into, as some of the data recorded after the start of the add call may or may not be added to the target histogram. This seems like an "always wrong to do" thing, unless you are OK with lossy or double-counted data effects. To avoid those, I'd recommend using a Recorder for patterns where you are looking to get a stable data view from a concurrent histogram you are continually recording into. E.g. add the

  Histogram intervalHistogram;
  ...
  accumulatedHistogram.add(intervalHistogram = Recorder.getIntervalHistogram(intervalHistogram));

Will probably do what you want. [Note: The reason to keep intervalHistogram around and pass it in each time is for efficient recycling. This way no histograms are allocated during sampling].

**Comment by slandelle** [comment]
Hi Gil,

Thanks a lot for the fix, I'll give it a try and will let you know.

> Separately, there is an obvious raciness to adding data from a concurrent histogram that is being actively recorded into, as some of the data recorded after the start of the add call may or may not be added to the target histogram. This seems like an "always wrong to do" thing, unless you are OK with lossy or double-counted data effects. To avoid those, I'd recommend using a Recorder for patterns where you are looking to get a stable data view from a concurrent histogram you are continually recording into.

Yes, I'm aware of that. My problem is that I have no was of telling if I might receive new measures for a given metric and I have to keep its Recorder around, or if I can/should discard it. As the number of different metrics I measure is unbound, I could end up with quite a memory leak. For now, I decided to live with missing some events.

Thanks!

**Comment by giltene** [comment]
If you were keeping a concurrent histogram instance around for each metric, then keeping the Recorder will not be fundamentally different from keeping the or a ConcurrentHistogram around for that metric. A (resizable) recorder will have two internal concurrent histograms, so it's only slightly fatter, but will have the same lifetime/lifecycle concerns.
And if you were using a shared concurrent histogram across your metrics, then you can use a shared Recorder for the same purpose instead.

**Comment by slandelle** [comment]
Sorry, it seems I wasn't clear.

I have a `ConcurrentHashMap<Key, ConcurrentHistogram>` where Key values can come again in the next seconds, or maybe 1 minute later, or maybe never. And there isn't a limit on the different values they can take. So, I can't keep them around forever.

**Comment by giltene** [comment]
@slandelle did you have a chance to verify the fix?

**Comment by slandelle** [comment]
Giving it a shot atm. Had to revert my workaround. Stay tuned.

**Comment by slandelle** [comment]
@giltene Fix seems to work, I haven't been able to reproduce the issue so far. I'll close it for now and will report back if we can reproduce in prod once we'll roll the next HdrHistogram release.

Thanks a lot!
