### ISSUE TITLE
Is it possible to have a sliding window of last x minutes?

### ISSUE THREAD

**Issue by whitehead1415** [HdrHistogram/HdrHistogram#89]
Can this be used to track the percentiles within a window of time?

Just wondering if/how it will work for streaming analytics.

**Comment by vitar** [comment]
Nope, but you can collect, flush and reset every X minutes by yourself.

**Comment by ahothan** [comment]
Implementing a sliding window would be pretty difficult if we want to keep the HdrHistogram core code simple and compact (and TBH it is clearly a bit of a luxury to do that) . Once you record an event it loses completely its timestamp.
I had the same requirement and a periodic flush as suggested by vitar works very well for me (we use a period of 5 seconds).

**Comment by mikeb01** [comment]
It depends how big you want your window to be and how small you wanted to quantise your time steps.  E.g. if you wanted a 1 minute window at 1 second granularity that would be fairly easy.  You would keep a ring buffer of 60 histograms, with each representing one second.  As a histogram expires you'd clear it and reuse it for the next minute.

To view the window, you would then aggregate across all of the histograms in the window.

**Comment by giltene** [comment]
The hdr_recorder (and the sisr Recorder mechanism in the Java version) has become the common way to deal with this sort of need: the recording path stays fast, non-blocking, and doesn't have to deal with periodically doing big pieces of work for one operation (e.g, zeroing in a flip). The observing path (typically on a different logging thread) periodically gets an interval histogram from the recorder. The recorder makes sure that no samples are lost, and that nothing is double counted. And this all fits into exactly what you need when you want to log behavior in interval histograms. The common logging format that the various language implementation support also fits into this picture pretty well.

We built the Recorder and hdr_tecorder after repeatedly jurry-rigging similar mechanisms in applications several times (sometimes inline in the recording path, sometimes with synchronization/locking/blocking, sometimes wait free), and found that the need seems to always be there. The "moving window" question is trivially addressed by an interval histogram log because histogram intervals are additive. So as long as you keep your interval period low enough, you can aggregate a moving window over a log to get any moving window (with overlaps) that you want...

**Comment by vladimir-bukhtoyarov** [comment]
@whitehead1415 It is impossible to get an accurate result using approximate algorithms. Restriction to storing any value accurate  **N** timeunits, is very strong restriction which can be satisfied only via  storing each value with its timestamp independently from other values and it can lead to high memory consumption. You should not to use HdrHistogram if you have so strong requirement.

But if restriction can be reduced to "at least N" or "at most N" then you can do it as Gill mention above. If you do not want to implement rotation from scratch then you can try to use
[metrics-core-hdr](https://github.com/vladimir-bukhtoyarov/metrics-core-hdr) or copy the algorithm of window rotation from [there](https://github.com/vladimir-bukhtoyarov/metrics-core-hdr/blob/master/src/main/java/com/github/metricscore/hdrhistogram/accumulator/ResetByChunksAccumulator.java)
```java
// Split reservoir by 7 chunks, each value written to reservoir will take affect to the snapshot approximately 60-70 seconds
  Histogram histogram = new HdrBuilder()
            .resetReservoirByChunks(Duration.ofSeconds(10), 7)
            buildHistorgam();  
```

**Comment by giltene** [comment]
To be clear, HdrHistograms do not contain any information about when (within an interval histogram, for example) specific values were seen. But if e.g. you are looking to report percentiles for the last N minutes (accurate to +/- 1 sec, and not including up to the past 1 second) you can easily do that with a histogram log and an hdr_recorder (or equivalent in other langs) hat logs interval histograms every 1 second. Since this is usually what people asking for this sort of thing (show me percentile reported over time span, rolling or not) want, the recorder, log format, and tools that can process it (like HistogramLogProcessor) give you a direct and simple way to do this.

**Comment by giltene** [comment]
@whitehead1415 looking to close the issue. Would you say that a pattern using a Recorder and a histogram log (or in-memory circular buffer of histograms) with "frequent enough" interval sampling provides a good enough answer for a "rolling window over the last X minutes" need [with +/- interval-sample-time resolution for what "the last X minutes" mean, obviously]?

**Comment by whitehead1415** [comment]
@giltene yes I am satisfied.
Thanks everyone for all the help!
