### ISSUE TITLE
README claims values as low as 0 can be recorded but that seems unsupported by the implementation

### ISSUE THREAD

**Issue by aweisberg** [HdrHistogram/HdrHistogram#91]
> For example, a Histogram could be configured to track the counts of observed integer values between 0 and 3,600,000,000 

This seems to be contradicted by this precondition in AbstractHistogram.java](https://github.com/HdrHistogram/HdrHistogram/blob/f4b5004799da6a8203554cea610f1b294caee37a/src/main/java/org/HdrHistogram/AbstractHistogram.java#L231).

It would be very nice to be able to record 0 values for distributions of things like size of a result set. Alternatively just update the README to reflect the actual behavior.

**Comment by giltene** [comment]
0 is absolutely a supported value. Always. The only question is "what else looks like a 0?". 
As the JavaDoc explains, lowestDiscernibleValue refers to the smallest value that can be discerned from 0. If it 1 by default, but you can create histograms with a larger lowestDiscernibleValue. E.g. when one wants to record latency in nanosecond units (e.g. so as not go have to convert nanoTime to some other unit when recording), but starting at a 1 usec resolution (e.g. because you don't want to spend the storage to track 1 nsec resolution stuff), you would create the histogram with a lowestDiscernibleValue of 1000. Such a histogram is allowed to consider all values from 0..999 as equivalent to 0 (in practice it would be 0..511 due to power of 2 internal stuff, but which satisfies the requirement since it is slightly more accurate).

**Comment by aweisberg** [comment]
You are right the documentation makes that very obvious. My mistake.
