### ISSUE TITLE
handleRecordException in log4j test

### ISSUE THREAD

**Issue by ceeaspb** [HdrHistogram/HdrHistogram#96]
similar to #46 handleRecordException is occurring in the log4j performance test written by @remkop when arrival rate > throughput and the logger cannot keep up causing recorded latency to tend to infinity.

Exception in thread "latencytest-0" java.lang.ArrayIndexOutOfBoundsException: value outside of histogram covered range. Caused by: java.lang.ArrayIndexOutOfBoundsException: 25601
at org.HdrHistogram.AbstractHistogram.handleRecordException(AbstractHistogram.java:441)
at org.HdrHistogram.AbstractHistogram.recordSingleValue(AbstractHistogram.java:431)
at org.HdrHistogram.AbstractHistogram.recordValue(AbstractHistogram.java:346)
at org.apache.logging.log4j.core.async.perftest.ResponseTimeTest.runLatencyTest(ResponseTimeTest.java:197)
at org.apache.logging.log4j.core.async.perftest.ResponseTimeTest.access$000(ResponseTimeTest.java:50)
at org.apache.logging.log4j.core.async.perftest.ResponseTimeTest$1.run(ResponseTimeTest.java:171)

The exception causes the test to end early, loosing data.

**Comment by giltene** [comment]
I don't think this is similar to https://github.com/HdrHistogram/HdrHistogram/issues/46. That was an actual race in ConcurrentHistogram resizing. This AIOOB is [IMO] a correct and expected behavior when recording a value that is larger than the max value configured in a histogram [that is not set to auto-resize]. The test (which I assume is https://github.com/apache/logging-log4j2/blob/master/log4j-core/src/test/java/org/apache/logging/log4j/core/async/perftest/ResponseTimeTest.java#L152) initializes the histograms with a max value of 10 seconds. So an overflow and an AIOOB is expected when you record a value larger than 10 seconds (which is very possible for response time measurements under load).

Your potential ways to deal with this are:
A) size your histograms with a max value that is longer than the the max expected run time of your tests (plus tons of padding) e.g. size them for 1 month, or 1 year.
B) Construct auto-resizing histograms by using the auto-resize constructor.
C) Use the current constructor (10 seconds), and then turn on auto-resize with histogram.setAutoResize(true);

For your case (a latency recording during load gen), I would go with either (A) or (C). While (B) will work, the auto-resize operation (when crossing a size threshold) will occur synchronously during value recording, slowing down the recording thread with an abnormally long recording call. The reason this is "probably ok" in (C) above is that the longer operation will only be incurred when recording an already very large value (e.g. 10 seconds), so the length of the longer recording operation (due to an auto-resize action) will still be a tiny fraction of the time that things actually took.

**Comment by ceeaspb** [comment]
Thanks for the detail.

Behaviour is correct and expected so it would be an improvement to change the error message to state that, or provide a hint. This will help users find the right course of action to avoid the issue.

A-C all have issues as you say. There is a simpler solution in the use of the max recordable value.

The latency here could end up being in theory infinity. So it is more a question of what is the max value that is of _interest_ to the test/result. If 10 seconds is the "max value of interest" then you don't need to record a value higher than that as there is no information in it. Resetting any value above 10 second to 10 seconds before recording it avoids the problems in A-C.

**Comment by giltene** [comment]
Given how storage costs work [largely due to the power of limiting to a specified decimal point accuracy], I highly encourage people to not overoptimize to use "small" limits on their histograms. E.g. a histogram that covers >  1 year with 1 nsec resolution and 3 decimal points of accuracy requires less than twice the internal storage as one that covers only up to 10 seconds... And one that covers MAX_LONG is only 2.2x as big as the one that covers 10 seconds. Your choice of accuracy has a much larger impact on storage needs than your choice of range. E.g. If you drop from 3 decimal points of accuracy to 2, your storage needs will drop by almost 8x. And "good to within 1% (in magnitude)" is usually plenty good enough for latency characterization.

**Comment by giltene** [comment]
Regarding the "change error message" suggestion/note: It already says pretty clearly "Exception in thread "latencytest-0" java.lang.ArrayIndexOutOfBoundsException: value outside of histogram covered range."
